name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10f5a1236c5c030ec7adb48b874339e9baa1f58634e2026930786be4c1a66439"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
