name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8bc77566be75887bf74f3b21cd1c1cfc92aa890681ab538541ef8f96148af9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
