name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "802fec8403e37731e9aaa3d3c50592121db2d3d8f67c7fa1a29a8e5c643fcf32"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
