name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.13.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98f229ef9b08bb02b3e21a14729d4814f8b13e95c28ac9dd48798770c6ce8113"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
