name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "134e8720efd3cbc65a3552e1ad64834bda280d7906e709c0376b209eaeb56fc2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
