name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.13.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35c8b53a88fd978919e16d220e02d1cb02f76219813c0213747bf1418f0b8a7f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
