name: Build

on:
  push:
    branches:
    - master-ceu

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"
    - name: Export Client Curse Pack
      shell: bash
      run: |
        chmod +x ./packwiz
        ./packwiz curseforge export -o client.zip
        mkdir -p ./buildOut/
        mv ./client.zip ./buildOut/
    - name: Bootstrap
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Install requests
      run: |
        pip install requests
    - run: python build/download.py
    - name: Download
      shell: bash
      run: |
          serverPack="server.zip"
  
          java -jar build/server/packwiz-installer-bootstrap.jar -g -s server pack.toml
  
          zip -r $serverPack config
          zip -r $serverPack groovy
          zip -r $serverPack mods
          zip -r $serverPack structures
          zip -m $serverPack launch.sh
  
          cd ..
  
          mv ./server/$serverPack buildOut/$serverPack
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'
    - run: java -version
    - name: Run Build
      run: |
        python build/main.py
      env:
        CFAPIKEY: ${{ secrets.CFAPIKEY }}
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ steps.vars.outputs.sha_short }}
          files: |
            buildOut/client.zip
            buildOut/server.zip
            buildOut/modlist.html

